apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 444307863991.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 444307863991.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 5d19b8a7
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
